#!/bin/bash

# List of Python scripts to test
python_scripts=(
    "0-add.py"
    "0-import_add.py"
    "1-calculation.py"
    "100-my_calculator.py"
    "101-easy_print.py"
    "102-magic_calculation.py"
    "103-fast_alphabet.py"
    "2-args.py"
    "3-infinite_add.py"
    "4-hidden_discovery.py"
    "5-variable_load.py"
    "add_0.py"
    "calculator_1.py"
    "push"
)

# Run tests
for script in "${python_scripts[@]}"; do
    echo "Testing $script"
    python3 "$script"
    echo "============================================"
done
